name: Deploy Storybook Demo Site
on:
  push:
    paths:
      - dragontail-components/src/**
      - .github/workflows/deploy-storybook.yml
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install Dependencies
        working-directory: ./dragontail-components
        run: yarn && yarn add-no-save react react-dom
      - name: Build Storybook App
        working-directory: ./dragontail-components
        run: yarn predeploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dragontail-components/storybook-static
